# Generated by Django 3.2.6 on 2022-02-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='json_result',
            field=models.TextField(blank=True, null=True, verbose_name='返回信息'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_body',
            field=models.TextField(blank=True, null=True, verbose_name='请求参数'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_browser',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='请求浏览器'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_ip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='请求ip地址'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='请求方式'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_modular',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='请求模块'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_msg',
            field=models.TextField(blank=True, null=True, verbose_name='操作说明'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_os',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='请求地址'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='response_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='响应状态码'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='status',
            field=models.BooleanField(default=False, verbose_name='响应状态'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单设置图标'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.IntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE'), (4, 'PATCH'), (5, 'OPTIONS')], default=1, verbose_name='接口请求方法'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='title',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='value',
            field=models.CharField(max_length=64, verbose_name='权限值'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=40, verbose_name='姓名'),
        ),
    ]
