# Generated by Django 3.2.6 on 2022-02-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_permission_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='value',
        ),
        migrations.AddField(
            model_name='permission',
            name='sort',
            field=models.CharField(default=1, max_length=64, verbose_name='权限排序'),
            preserve_default=False,
        ),
    ]
