# Generated by Django 3.2.6 on 2022-02-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20220209_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.IntegerField(default=1, max_length=64, verbose_name='权限排序'),
        ),
    ]
