# Generated by Django 3.2.6 on 2022-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_permission_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='权限排序'),
        ),
    ]
